#dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp-pod
  labels:
    app: simpleapp
spec:
      containers:
        - name: simpleapp
          image: bathurudocker/simpleapp:latest
          ports:
            - containerPort: 8080
